import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { ClerkProvider } from "@clerk/nextjs";
import TopNav from "./_components/topnav";

export const metadata = {
  title: "Gallery",
  description: "Generated by create t3-app by Theo on YouTube",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <ClerkProvider>
        <body className="flex flex-col gap-4">
          <div className="w-full">
            <TopNav />
          </div>
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
